In [1]:
# import packages and set options

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from datetime import datetime
pd.set_option('display.max_rows', 20)

In [2]:
# read data in

games_df = pd.read_csv('games.csv')
players_df = pd.read_csv('players.csv')
plays_df = pd.read_csv('plays.csv')
tackles_df = pd.read_csv('tackles.csv')
tracking_week_1_df = pd.read_csv('tracking_week_1.csv')
tracking_week_2_df = pd.read_csv('tracking_week_2.csv')
tracking_week_3_df = pd.read_csv('tracking_week_3.csv')
tracking_week_4_df = pd.read_csv('tracking_week_4.csv')
tracking_week_5_df = pd.read_csv('tracking_week_5.csv')
tracking_week_6_df = pd.read_csv('tracking_week_6.csv')
tracking_week_7_df = pd.read_csv('tracking_week_7.csv')
#tracking_week_8_df = pd.read_csv('tracking_week_8.csv')
#tracking_week_9_df = pd.read_csv('tracking_week_9.csv')

In [3]:
# merge all available data to tracking data

one_merge = pd.merge(tracking_week_1_df, games_df, on='gameId')
two_merge = pd.merge(one_merge, players_df, on='nflId')
three_merge = pd.merge(two_merge, plays_df, on=['gameId', 'playId'])
final_merge = pd.merge(three_merge, tackles_df, on=['gameId', 'playId', 'nflId'], how="left")
final_merge.head()

# dropping about 61193 frames because of missing/unexplained data
# tracking_week_1_df[tracking_week_1_df["displayName"] == "football"]

,gameId,playId,nflId,displayName_x,frameId,time,jerseyNumber,club,playDirection,x,...,expectedPoints,expectedPointsAdded,foulName1,foulName2,foulNFLId1,foulNFLId2,tackle,assist,forcedFumble,pff_missedTackle
0,2022090800,56,35472.0,Rodger Saffold,1,2022-09-08 20:24:05.200000,76.0,BUF,left,88.37,...,1.298699,0.00442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022090800,56,35472.0,Rodger Saffold,2,2022-09-08 20:24:05.299999,76.0,BUF,left,88.47,...,1.298699,0.00442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022090800,56,35472.0,Rodger Saffold,3,2022-09-08 20:24:05.400000,76.0,BUF,left,88.56,...,1.298699,0.00442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022090800,56,35472.0,Rodger Saffold,4,2022-09-08 20:24:05.500000,76.0,BUF,left,88.64,...,1.298699,0.00442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022090800,56,35472.0,Rodger Saffold,5,2022-09-08 20:24:05.599999,76.0,BUF,left,88.72,...,1.298699,0.00442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN